spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.liquibase.enabled=false

jwt.expiration=1800000
jwt.secret=secretkeydfhgdofhfgodfhgohgodhfoghgod
server.servlet.context-path=/api
server.port=${PORT:8080}

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.root=DEBUG
logging.level.org.apache.fontbox=INFO

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anatolyign@gmail.com
spring.mail.password=${APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# CORS
cors.allowed-origins=https://slon7716.github.io

spring.http.encoding.enabled=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true
